### ISSUE TITLE
【Members】入力したいテキストフィールドに入力できないバグ

### ISSUE THREAD

**Issue by Tomoch0104** [Team-CrazyDiamond/SeatAssist#47]
たまに指定したテキストフィールドに文字を打っているはずなのに別のメンバーのテキストフィールドに入力が反映されるバグを発見

**Comment by Rakalute** [comment]
このバグはすでに直っていると思うので，確認お願いします！

**Comment by Tomoch0104** [comment]
使い倒しテストで確認しましたが，おそらく治っているみたいです！！
